package reporter

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/AnassElhamri/ssh-honeypot/internal/logger"
)

// Reporter generates periodic HTML and Markdown reports.
type Reporter struct {
	db        *logger.DB
	outputDir string
}

// New creates a Reporter.
func New(db *logger.DB, outputDir string) *Reporter {
	os.MkdirAll(outputDir, 0755)
	return &Reporter{db: db, outputDir: outputDir}
}

// GenerateReport creates a full report for the given time window.
func (r *Reporter) GenerateReport() error {
	stats, err := r.db.GetStats()
	if err != nil {
		return fmt.Errorf("fetch stats: %w", err)
	}

	md   := r.buildMarkdown(stats)
	html := r.buildHTML(stats)
	json := r.buildJSON(stats)

	ts       := time.Now().Format("2006-01-02_15-04-05")
	mdPath   := filepath.Join(r.outputDir, fmt.Sprintf("report_%s.md", ts))
	htmlPath := filepath.Join(r.outputDir, fmt.Sprintf("report_%s.html", ts))
	jsonPath := filepath.Join(r.outputDir, fmt.Sprintf("report_%s.json", ts))

	if err := os.WriteFile(mdPath, []byte(md), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(htmlPath, []byte(html), 0644); err != nil {
		return err
	}
	if err := os.WriteFile(jsonPath, []byte(json), 0644); err != nil {
		return err
	}

	fmt.Printf("Report saved:\n  %s\n  %s\n  %s\n", mdPath, htmlPath, jsonPath)
	return nil
}

// StartScheduler runs the reporter on a schedule (daily/hourly).
func (r *Reporter) StartScheduler(schedule string) {
	var interval time.Duration
	switch schedule {
	case "hourly":
		interval = time.Hour
	default:
		interval = 24 * time.Hour
	}

	go func() {
		ticker := time.NewTicker(interval)
		defer ticker.Stop()
		for range ticker.C {
			r.GenerateReport()
		}
	}()
}

func (r *Reporter) buildMarkdown(stats *logger.Stats) string {
	var sb strings.Builder
	now := time.Now().Format("2006-01-02 15:04:05 UTC")

	sb.WriteString(fmt.Sprintf("# SSH Honeypot Report\n\n"))
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", now))
	sb.WriteString("---\n\n")

	// Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("| Metric | Value |\n|--------|-------|\n"))
	sb.WriteString(fmt.Sprintf("| Total Sessions | %d |\n", stats.TotalSessions))
	sb.WriteString(fmt.Sprintf("| Unique IPs | %d |\n", stats.UniqueIPs))
	sb.WriteString(fmt.Sprintf("| Total Credential Attempts | %d |\n", stats.TotalCredentials))
	sb.WriteString(fmt.Sprintf("| Total Commands Executed | %d |\n\n", stats.TotalCommands))

	// Top passwords
	sb.WriteString("## Top 10 Passwords Tried\n\n")
	sb.WriteString("| Rank | Password | Count |\n|------|----------|-------|\n")
	for i, e := range stats.TopPasswords {
		sb.WriteString(fmt.Sprintf("| %d | `%s` | %d |\n", i+1, e.Value, e.Count))
	}
	sb.WriteString("\n")

	// Top usernames
	sb.WriteString("## Top 10 Usernames Tried\n\n")
	sb.WriteString("| Rank | Username | Count |\n|------|----------|-------|\n")
	for i, e := range stats.TopUsernames {
		sb.WriteString(fmt.Sprintf("| %d | `%s` | %d |\n", i+1, e.Value, e.Count))
	}
	sb.WriteString("\n")

	// Top countries
	sb.WriteString("## Top 10 Attack Origins\n\n")
	sb.WriteString("| Rank | Country | Sessions |\n|------|---------|----------|\n")
	for i, e := range stats.TopCountries {
		sb.WriteString(fmt.Sprintf("| %d | %s | %d |\n", i+1, e.Value, e.Count))
	}
	sb.WriteString("\n")

	// Recent sessions
	sb.WriteString("## Recent Sessions (Last 20)\n\n")
	sb.WriteString("| ID | IP | Country | Creds | Cmds | Threat | Duration |\n")
	sb.WriteString("|----|----|---------|----|------|--------|----------|\n")
	for _, sess := range stats.RecentSessions {
		duration := "active"
		if sess.EndTime != nil {
			duration = sess.EndTime.Sub(sess.StartTime).Round(time.Second).String()
		}
		sb.WriteString(fmt.Sprintf("| %d | %s | %s | %d | %d | %d | %s |\n",
			sess.ID, sess.IP, sess.Country,
			sess.TotalCreds, sess.TotalCmds,
			sess.ThreatScore, duration))
	}

	sb.WriteString("\n---\n*Generated by SSH Honeypot — github.com/AnassElhamri/ssh-honeypot*\n")
	return sb.String()
}

func (r *Reporter) buildHTML(stats *logger.Stats) string {
	now := time.Now().Format("2006-01-02 15:04:05 UTC")

	topPasswords := ""
	for i, e := range stats.TopPasswords {
		topPasswords += fmt.Sprintf(`<tr><td>%d</td><td><code>%s</code></td><td>%d</td></tr>`,
			i+1, e.Value, e.Count)
	}

	topUsernames := ""
	for i, e := range stats.TopUsernames {
		topUsernames += fmt.Sprintf(`<tr><td>%d</td><td><code>%s</code></td><td>%d</td></tr>`,
			i+1, e.Value, e.Count)
	}

	topCountries := ""
	for i, e := range stats.TopCountries {
		topCountries += fmt.Sprintf(`<tr><td>%d</td><td>%s</td><td>%d</td></tr>`,
			i+1, e.Value, e.Count)
	}

	recentSessions := ""
	for _, sess := range stats.RecentSessions {
		duration := "active"
		if sess.EndTime != nil {
			duration = sess.EndTime.Sub(sess.StartTime).Round(time.Second).String()
		}
		threatClass := "low"
		if sess.ThreatScore >= 75 { threatClass = "critical" } else
		if sess.ThreatScore >= 50 { threatClass = "high" } else
		if sess.ThreatScore >= 25 { threatClass = "medium" }

		recentSessions += fmt.Sprintf(
			`<tr><td>%d</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td>`+
			`<td class="threat-%s">%d</td><td>%s</td></tr>`,
			sess.ID, sess.IP, sess.Country,
			sess.TotalCreds, sess.TotalCmds,
			threatClass, sess.ThreatScore, duration)
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SSH Honeypot Report — %s</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0d1117; color: #e6edf3; padding: 2rem; }
  h1 { color: #58a6ff; font-size: 1.8rem; margin-bottom: 0.5rem; }
  h2 { color: #8b949e; font-size: 1.1rem; margin: 2rem 0 1rem; border-bottom: 1px solid #21262d; padding-bottom: 0.5rem; }
  .meta { color: #6e7681; font-size: 0.9rem; margin-bottom: 2rem; }
  .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .stat-card { background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 1.2rem; text-align: center; }
  .stat-card .value { font-size: 2rem; font-weight: bold; color: #58a6ff; }
  .stat-card .label { font-size: 0.85rem; color: #8b949e; margin-top: 0.3rem; }
  table { width: 100%%; border-collapse: collapse; background: #161b22; border-radius: 8px; overflow: hidden; }
  th { background: #21262d; padding: 0.7rem 1rem; text-align: left; color: #8b949e; font-size: 0.85rem; text-transform: uppercase; }
  td { padding: 0.6rem 1rem; border-top: 1px solid #21262d; font-size: 0.9rem; }
  tr:hover td { background: #1c2128; }
  code { background: #21262d; padding: 0.15rem 0.4rem; border-radius: 4px; font-family: monospace; color: #f78166; }
  .threat-low { color: #3fb950; }
  .threat-medium { color: #d29922; }
  .threat-high { color: #f85149; }
  .threat-critical { color: #ff7b72; font-weight: bold; }
  footer { margin-top: 3rem; text-align: center; color: #6e7681; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>⚠ SSH Honeypot Report</h1>
<p class="meta">Generated: %s</p>

<div class="stats-grid">
  <div class="stat-card"><div class="value">%d</div><div class="label">Total Sessions</div></div>
  <div class="stat-card"><div class="value">%d</div><div class="label">Unique IPs</div></div>
  <div class="stat-card"><div class="value">%d</div><div class="label">Credential Attempts</div></div>
  <div class="stat-card"><div class="value">%d</div><div class="label">Commands Executed</div></div>
</div>

<h2>Top 10 Passwords Tried</h2>
<table><tr><th>#</th><th>Password</th><th>Count</th></tr>%s</table>

<h2>Top 10 Usernames Tried</h2>
<table><tr><th>#</th><th>Username</th><th>Count</th></tr>%s</table>

<h2>Top Attack Origins</h2>
<table><tr><th>#</th><th>Country</th><th>Sessions</th></tr>%s</table>

<h2>Recent Sessions</h2>
<table>
<tr><th>ID</th><th>IP</th><th>Country</th><th>Creds</th><th>Cmds</th><th>Threat</th><th>Duration</th></tr>
%s
</table>

<footer>Generated by SSH Honeypot — <a href="https://github.com/AnassElhamri/ssh-honeypot" style="color:#58a6ff">github.com/AnassElhamri/ssh-honeypot</a></footer>
</body></html>`,
		now, now,
		stats.TotalSessions, stats.UniqueIPs,
		stats.TotalCredentials, stats.TotalCommands,
		topPasswords, topUsernames, topCountries, recentSessions,
	)
}

func (r *Reporter) buildJSON(stats *logger.Stats) string {
	data, _ := json.MarshalIndent(stats, "", "  ")
	return string(data)
}
